language: node_js
node_js:
- 8.9.4
sudo: required
dist: trusty
before_script:
- "sudo chown root /opt/google/chrome/chrome-sandbox"
- "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
cache:
  directories:
  - clientApp/node_modules
before_install:
- cd clientApp
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
install:
- npm install
- ng build
scripts:
- export CHROME_BIN=chromium-browser
- npm run lint:ci
- npm run test:ci -- --watch false --single-run true
